<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\aspireSample.ServiceDefaults\aspireSample.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\ElBruno.MAF.FoundryLocal\ElBruno.MAF.FoundryLocal.csproj" />
  </ItemGroup>

</Project>
